vl_crud:
    resource: "@VLCrudBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:    /login
    defaults: {_controller: VLUserBundle:Security:login }

login_check:
    path:    /login_check

logout:
    path:    /logout
